### ISSUE TITLE
jinja2 support does not work (MP 0.10)

### ISSUE THREAD

**Issue by mjmare** [morepath/morepath#323]
It seems a config.scan(more.jinja2) is in order (not obvious to newbie).
Furthermore two dependencies have to be satisfied manually: webtest and pytest.
Finally when trying to run my app I get a traceback. It seems to want a template person.jinja2 template, which does not exist in my app (but does in the more.jinja2 tests).

```
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/bin/project-start", line 9, in <module>
    load_entry_point('dashboard==0.0.0', 'console_scripts', 'project-start')()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/dashboard/main.py", line 37, in main
    config.commit()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 538, in commit
    configurable.execute()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 104, in execute
    actions.perform(self)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 175, in perform
    action.perform(configurable, obj)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/directive.py", line 564, in perform
    self.permission, self.internal)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/view.py", line 49, in register_view
    render = registry.get_template_render(template, render)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/template.py", line 63, in get_template_render
    return get_render(loader, name, original_render)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/more.jinja2-0.2-py2.7.egg/more/jinja2/main.py", line 35, in get_jinja2_render
    template = loader.get_template(name)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/loaders.py", line 178, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: person.jinja2
```

**Comment by href** [comment]
Looks like the configuration step is failing because it tries to scan the tests. Can you try scanning more.jinja2 like this?:

    config.scan(more.jinja2, ignore=('.test', '.tests'))

I agree that this is not obvious to a newbie. I had a brief look at the quickstart, more.jinja2 and templating docs and none of them mention `config.scan`, `morepath.autoconfig` or `morepath.autoscan`.

You might want to have a look at those:
* http://morepath.readthedocs.org/en/latest/api.html#morepath.autosetup
* http://morepath.readthedocs.org/en/latest/api.html#morepath.autoconfig

**Comment by faassen** [comment]
Thanks @href for looking into this, hopefully this does fix the underlying issue.

We do need at the very least improve the documentation so that this is more clear -- the places you point out need a bit of adjustment.

Maybe we want to introduce a slightly higher-level `config.load()` or something like that which automatically ignores tests, and then adjust the docs so we point to it everything. `config.scan` can then be the lower-level tool, which is probably still needed inside test code and such. What do you think?

**Comment by href** [comment]
Why not just have config.scan include `ignore=('.test', '.tests')` as defaults (and everywhere else where we have `ignore`). Instead of introducing yet another config method.

**Comment by faassen** [comment]
Good question.  We don't want it to ignore tests in some cases so we'd need to tell people that in tests they'd need to use `config.scan(ignore=[])`, though perhaps even that is not required, as scanning of test fixtures would be happening inside the tests directory already.

**Comment by href** [comment]
Well I would argue that scanning without tests is the more common case. Testing is usually a separate subject anyway and would deserve it's own page in the docs.

**Comment by faassen** [comment]
The next step is to experimentally add the default ignores to the Morepath scan method and see whether it breaks any Morepath tests when we do so.

**Comment by mjmare** [comment]
I can confirm that with MP 0.10 switching to more path.autosetup() instead of manual scan "just works". Same for autoconfig+commit. 
A manual scan with config.scan(more.jinja2, ignore=('.test', '.tests') also works. 

All this scanning stuff could do with some documentation love. autoconfig is not mentioned in the narrative docs (only in API section). 
As I now understand the 3 setup scenarios are:
morepath.setup + config.scan + config.commit     (does not ignore tests)
morepath.autoconfig + config.commit                    (ignores tests, for package only)
morepath.autosetup                                               (ignores tests, for package only)

**Comment by faassen** [comment]
You're very right, this does need more documentation love. Thanks @href for creating an issue on it!

**Comment by faassen** [comment]
Since we now have issues on the followup topics and @mjmare can proceed, I'll close this issue. Thanks for this valuable feedback, @mjmare !
