### ISSUE TITLE
Improve error message for morepath.error.ConflictError

### ISSUE THREAD

**Issue by mjmare** [morepath/morepath#330]
By accident I had two config sections in my code with identical decorators:
```
@BaseApp.setting_section(section='config')
def ba_get_setting_section():
    return {
        'neo4j_uri': 'http://localhost:7474/db/data',
    }

@BaseApp.setting_section(section='config')  # should have been @TestingApp....
def ta_get_setting_section():
    return {
        'neo4j_uri': 'http://localhost:8484/db/data',
    }
```
This yields a morepath.error.ConflictError in the autosetup() phase. That's very nice but the description is empty, so finding the cause of the error is harder than it could be.

```
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/bin/project-start", line 9, in <module>
    load_entry_point('dashboard==0.0.0', 'console_scripts', 'project-start')()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/dashboard/main.py", line 98, in main
    autosetup()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/autosetup.py", line 104, in autosetup
    c.commit()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 538, in commit
    configurable.execute()
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 103, in execute
    actions.prepare(self)
  File "/Users/mjm/Dropbox/Devel/Morepath/dashboard_project/venv/lib/python2.7/site-packages/morepath-0.10-py2.7.egg/morepath/config.py", line 144, in prepare
    raise ConflictError([action, other_action])
morepath.error.ConflictError: Conflict between:
```

**Comment by href** [comment]
I can confirm. The error is more helpful if the `setting` directive is causing the conflict instead of the `setting_section` directive.

**Comment by faassen** [comment]
Hm, that's indeed not pretty.

The code that generates that message is on a very hard to test code path, unfortunately. I suspect something is going on that just causes the actual line numbers not to be supplied properly when setting_section is in use. I wonder how easy it will be to fix. I'll put it in for 0.11 so we at least review it before then.
